name: "baysor_segfree"
description: Extract neighborhood composition vectors (NVCs) from a dataset.
keywords:
  - neighborhood
  - baysor
  - segmentation_free
tools:
  - "baysor":
    description: "Baysor is a tool that segments cells using spatial gene expression maps. Optionally, segmentation masks can be given as additional input."
    homepage: "https://kharchenkolab.github.io/Baysor/dev/"
    documentation: "https://kharchenkolab.github.io/Baysor/dev/"
    tool_dev_url: "https://github.com/kharchenkolab/Baysor"
    doi: "https://doi.org/10.1038/s41587-021-01044-w"
    licence: ["MIT license"]
    identifier:

## baysor_segfree requires a transcript map of the data and a configuration file with argument values
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - transcripts_csv:
        type: file
        description: CSV file
        pattern: "*.csv"
    - config_toml:
        type: file
        description: TOML file with config arguments
        pattern: "*.toml"

## neighborhood composition vectors
output:
  ncvs:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
    - "${prefix}/ncvs.loom":
        type: file
        description: |
          Segmenation file in loom format
        pattern: "${prefix}/ncvs.loom"

  versions_baysor:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - python:
          type: string
          description: The tool name
      - "baysor --version 2>&1 | grep -oP '\\d+\\.\\d+\\.\\d+' || echo unknown":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - python:
          type: string
          description: The tool name
      - "baysor --version 2>&1 | grep -oP '\\d+\\.\\d+\\.\\d+' || echo unknown":
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@sebgoti8"
  - "@khersameesh24"
maintainers:
  - "@sebgoti8"
  - "@khersameesh24"
