---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  # procps-ng provides `ps`, required by Nextflow for task-metric collection
  - conda-forge::procps-ng=4.0.4
  - conda-forge::python=3.11.0
  - conda-forge::quarto=1.6.42
  - conda-forge::numpy=2.3.3
  - conda-forge::pandas=2.3.2
  - conda-forge::pyyaml=6.0.3
  - conda-forge::ipython=9.5.0
  - conda-forge::ipykernel=6.30.1
  - conda-forge::jupyter=1.1.1
  - conda-forge::papermill=2.6.0
