---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.10
  - tifffile
  - matplotlib
  - pip
  - pip:
      - scportrait

container:
  - community.wave.seqera.io/library/pip_scportrait:e0651f1fbb601e73
