---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "scportrait"
description: Generatation of single-cell representations from raw microscopy images
keywords:
  - image analysis
  - spatial omics
  - image representation
tools:
  - "scportrait":
      description: "	Computational framework to generate single cell datasets from raw microscopy images."
      homepage: "https://github.com/MannLabs/scPortrait/tree/main"
      documentation: "https://github.com/MannLabs/scPortrait/blob/main/README.md"
      tool_dev_url: "https://github.com/MannLabs/scPortrait"
      doi: "10.1101/2023.06.01.542416"
      licence: "Apache-2.0"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1' ]`

  - sdata:
      type: file
      description: SpatialData object (Zarr or H5AD) with image and segmentation masks
      pattern: "*.{zarr,h5ad}"

  - cell_id_identifier:
      type: string
      description: Optional column name in the segmentation table that links to cell masks
      optional: true

output:
  - masks:
    - meta:
        type: map
        description: Groovy Map containing sample information
    - "*_masks.tif":
        type: file
        description: Segmentation mask visualization generated by scPortrait
        pattern: "*_masks.tif"

  - images:
    - meta:
        type: map
        description: Groovy Map containing sample information
    - "*_cells.png":
        type: file
        description: Visualization of extracted single-cell images
        pattern: "*_cells.png"

  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@brovolia"
maintainers:
  - "@brovolia"
