name: "parquet_to_csv"
description: Convert parquet file to CSV for tools with old Parquet readers.
keywords:
  - xenium
  - parquet
  - csv
  - transcripts
tools:
  - "pyarrow":
      description: |
        Python library providing a Pythonic API for Apache Arrow,
        including fast Parquet and CSV I/O.
      homepage: "https://arrow.apache.org/docs/python/"
      documentation: "https://arrow.apache.org/docs/python/"
      tool_dev_url: "https://github.com/apache/arrow"
      doi: "no DOI available"
      licence: ["Apache-2.0"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - parquet:
        type: file
        description: Parquet file to convert.
        pattern: "*.parquet"
        ontologies: []

output:
  csv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - "transcripts.csv":
          type: file
          description: Converted CSV file.
          pattern: "transcripts.csv"
          ontologies: []
  versions_pyarrow:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - pyarrow:
          type: string
          description: The tool name
      - "python3 -c 'import pyarrow; print(pyarrow.__version__)'":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - pyarrow:
          type: string
          description: The tool name
      - "python3 -c 'import pyarrow; print(pyarrow.__version__)'":
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@an-altosian"
maintainers:
  - "@an-altosian"
