# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "segger_create_train_predict"
description: |
  segger is a cutting-edge tool for cell segmentation in single-molecule spatial omics datasets,
  subworkflow is the implementation of segger modules run in the recommended sequence
keywords:
  - segger
  - segmentation
  - xeniumranger import-segmentation
  - coordinate-based segmentation
components:
  - segger
  - segger/create/dataset
  - segger/train
  - segger/predict
  - segger2xr
  - xeniumranger/import/segmentation
input:
  - ch_bundle_path:
      description: |
        Directory containing the raw dataset - xenium bundle (e.g., transcripts, boundaries).
        Structure: [ val(meta), path("path-to-xenium-bundle") ]
  - ch_transcripts_parquet:
      description: |
        input parquet file from the xenium bundle
        Structure: [ val(meta), path("path-to-transcripts.parquet") ]
output:
  - datasetdir:
      description: |
        Directory generated by the segger create dataset module
        Structure: [ val(meta), path(datasetdir) ]
  - trained_models:
      description: |
        The model trained on the data by the segger training module
        Structure: [ val(meta), path(trained_models) ]
  - benchmarks:
      description: |
        benchmarks generated from the segger training and prediction steps
        Structure: [ val(meta), path(benchmarks) ]
  - segger_transcripts:
      description: |
        transcripts parquet file generated after segger prediction conatining the segger ids
        Structure: [ path(transcripts.parquet) ]
  - coordinate_space:
      description: |
        the coordinate space in which xeniumranger import-segmentation was run
        Structure: [ val("pixels") ]
  - redefined_bundle:
      description: |
        the redefined xenium bundle generated with the segmentation results from baysor
        Structure: [ val(meta), ["redefined-xenium-bundle"] ]
authors:
  - "@khersameesh24"
maintainers:
  - "@khersameesh24"
