# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "opt_flip_track_stat"
description: opt is a simple program that aligns probe sequences to transcript sequences
  to detect potential off-target probe activity
keywords:
  - opt
  - flip
  - track
  - stat
  - off-target probes
components:
  - opt/flip
  - opt/track
  - opt/stat
input:
  - ch_probe_fasta:
      type: file
      description: |
        Input channel containing the sample info. and associated probe panel sequences fasta file
        Structure: [ val(meta), path("porbe_panel_seqeunces.fasta") ]
      pattern: "*.fasta"
  - ch_references:
      type: file
      description: |
        Input channel containing the sample info. and the references to be used
        Structure: [ val(meta), path("reference_annotations.gff"), path("reference_annotations.fa") ]
      pattern: "*.{fa,gff}"
  - ch_gene_synonyms:
      type: file
      description: |
        Input channel containing the Gene synonyms that may have been counted as off-targets but
        simply differ in name (optional input)
        Structure: [ val(meta), path("gene_synonyms.csv") ]
      pattern: "*.csv"
output:
  - summary:
      type: file
      description: |
        Groovy Map containing summary of the forward oriented probes generated with the panel sequences opt flip and track
        Structure: [ val(meta), path("collapsed_summary.tsv") ]
      pattern: "*.tsv"
authors:
  - "@khersameesh24"
maintainers:
  - "@khersameesh24"
